# TODO
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-aws-credentials
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/part-of: togglemaster
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "CHANGEME"
  AWS_SECRET_ACCESS_KEY: "CHANGEME"
