apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/part-of: togglemaster
data:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service:8001"
