apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: togglemaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-service
        app.kubernetes.io/part-of: togglemaster
    spec:
      containers:
        - name: analytics-service
          image: 678054141550.dkr.ecr.us-east-1.amazonaws.com/analytics-service:v1.0.0-777ea98
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-service-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
