apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::678054141550:role/togglemaster-analytics-service
