# TODO
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secrets
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/part-of: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://CHANGEME:CHANGEME@CHANGEME-rds-endpoint:5432/targetingdb"
