apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: targeting-service-secrets
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: targeting-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgres://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .dbname }}"
  data:
    - secretKey: username
      remoteRef:
        key: togglemaster-targeting-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: togglemaster-targeting-db-credentials
        property: password
    - secretKey: host
      remoteRef:
        key: togglemaster-targeting-db-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: togglemaster-targeting-db-credentials
        property: port
    - secretKey: dbname
      remoteRef:
        key: togglemaster-targeting-db-credentials
        property: dbname
